### PR TITLE
Allow selecting track numbers to demux

### PR DESCRIPTION
**Pull request by quietvoid**
Hi.
I'm trying to implement specific track number demuxing, because I only need the video.
Currently, the demuxer panics when it encounters audio (at least with my test file that contains E-AC-3) while reading the headers/tracks:
```
thread 'main' panicked at 'not implemented', av-data-0.2.2/src/audiosample.rs:255:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

So far the patch seems to work, however EOF is encountered prematurely when demuxing the first (video) track only.
So the demuxing ends at ~150 000 packets when I'm expecting around ~170 000.
I haven't looked yet as to why, but am still creating this as a draft to hopefully get some help or insight.

### CODE REVIEW

**Comment by lu-zero** [comment]
Thank you a lot :) I'll look at it soon.

**Comment by lu-zero** [comment]
I wonder if it isn't more robust make it part of the demuxing higher level layer and parse and then discard.

**Comment by quietvoid** [comment]
> I wonder if it isn't more robust make it part of the demuxing higher level layer and parse and then discard.

I'm not too sure what you mean with this. As a DemuxerParams struct, it is already high level?

I've tried debugging the EOF issue I'm having and this might be more complicated than I thought.
While I can filter out SimpleBlocks parsed for a specific track number (without discarding the other tracks), the final count is different when parsing the full file compared to a file that only contains the video track.

**Comment by quietvoid** [comment]
I made this ready since the bug I'm encountering doesn't seem to be related to the new code.

**Review by lu-zero — COMMENTED** [review]
@Luni-4 I'd like a second opinion. shall we make it per-demuxer or as a higher level api feature?

**Comment by Luni-4** [comment]
> @Luni-4 I'd like a second opinion. shall we make it per-demuxer or as a higher level api feature?

@lu-zero 
Would an higher level API feature be used for muxing also?

**Comment by lu-zero** [comment]
The higher level API is the one used in `ave`. Probably we can land this now and consider the higher level later.

**Comment by quietvoid** [comment]
Thanks!

**Pull request merged**
