### PR TITLE
nom5 support

### PR DESCRIPTION
**Pull request by gibix**
Signed-off-by: gibix <gibix@riseup.net>

### CODE REVIEW

**Comment by Geal** [comment]
I'll add a custom error type to that

**Comment by Geal** [comment]
alright, it looks like it works :)
Now that we have a dedicated enum, maybe we should replace the error codes with proper enum variants?
The port to the new cookie-factory will have to wait a bit, we're still looking into some API changes

**Comment by lu-zero** [comment]
I guess we can land this part then :)

**Comment by lu-zero** [comment]
I'd squash and merge it today, anybody against it?

(PS: anybody willing to fix appveyor missing gcc?)

**Comment by Geal** [comment]
it should be fine to merge

**Comment by lu-zero** [comment]
Looks like github squash engine has a broken logic.

**Pull request merged**
