### PR TITLE
Improve matroska_info output

### PR DESCRIPTION
**Pull request by FreezyLemon**
1. Fix some small things (capitalization/wording)
2. Fix duration formatting
3. Fix segment UID formatting

### CODE REVIEW

**Review by lu-zero — APPROVED** [review]
Looks a nice improvement, thank you!

**Comment by lu-zero** [comment]
If you open a PR about the clippy lints I'd merge it first, but either that way or with an additional commit to fix the other lints is welcome :)

**Comment by FreezyLemon** [comment]
I opened #99 for the clippy warnings, and I guess I'll rebase (or merge, if you prefer) after that has been merged.

**Comment by lu-zero** [comment]
Hopefully github learned how to rebase :)

**Pull request merged**
